# References:
#
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#setting-up-a-cooldown-period-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    # Use a cooldown to wait for updates to become stable before applying them.
    # This helps to mitigate npm attacks, because the more time has elapsed
    # since an attack was published, the more likely it has been discovered and
    # removed. Major and minor updates are also further slowed to reduce churn
    # and review time.
    #
    # Note that known security updates always bypass this cooldown.
    cooldown:
      default-days: 7
      semver-patch-days: 7
      semver-minor-days: 14
      semver-major-days: 21
    groups:
      # Minor and patch changes should in theory never be breaking, so let's
      # consolidate them into a single PR so that they can be merged together.
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          # TypeScript doesn't follow semver, because it regularly publishes
          # breaking changes (e.g. stricter type-checking) as minor updates.
          - typescript

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
