[package]
name = "jsandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
rquickjs = { version = "0.6.2", default-features = false, features = [ "loader", "futures"] }

thiserror = "1.0.65"
paste = "1.0"
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }

[workspace.dependencies]
wasm-bindgen = { git = "https://github.com/surma-dump/wasm-bindgen.git", branch = "wasi" }
wasm-bindgen-cli-support = { git = "https://github.com/surma-dump/wasm-bindgen.git", branch = "wasi" }
wasm-bindgen-futures = { git = "https://github.com/surma-dump/wasm-bindgen.git", branch = "wasi" }
js-sys = { git = "https://github.com/surma-dump/wasm-bindgen.git", branch = "wasi" }



[workspace]
members = [
  "buildscript",
]
resolver = "2"
